version: '3.9'

networks:
  bpi-traefik:
    external: true

services:
  node:
    container_name: bpi-front-node
    image: bpi-front-node
    entrypoint: /entrypoint.sh
    build:
      context: ./
      dockerfile: ./.docker/node/dockerfile
    expose:
      - 3000
    volumes:
      - "${HOME}/.cache:/home/docker/.cache"
      - "${HOME}/.npm:/home/docker/.npm"
      - ./.docker/node/entrypoint.sh:/entrypoint.sh
      - ./.:/app
    networks:
      - bpi-traefik

  nginx:
    container_name: bpi-front-nginx
    build:
      context: ./
      dockerfile: ./.docker/nginx/dockerfile
      args:
        - SITE_HOST
    volumes:
      - "${HOME}/.cache:/home/docker/.cache"
      - "${HOME}/.composer:/home/docker/.composer"
      - "${HOME}/.npm:/home/docker/.npm"
      - ./.:/app
    expose:
      - 80
    depends_on:
      - node
    networks:
      - bpi-traefik
    labels:
      - traefik.enable=true
      - traefik.docker.network=bpi-traefik
      - traefik.http.routers.${APP_NAME}.rule=Host(`${SITE_HOST}`)
      - traefik.http.routers.${APP_NAME}.entrypoints=http
